DROP TABLE IF EXISTS citas CASCADE;
DROP TABLE IF EXISTS productos CASCADE;
DROP TABLE IF EXISTS servicios CASCADE;
DROP TABLE IF EXISTS usuarios CASCADE;

CREATE TABLE usuarios (
  id SERIAL PRIMARY KEY,
  email VARCHAR(100) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  nombre VARCHAR(100) NOT NULL,
  telefono VARCHAR(20),
  rol VARCHAR(10) NOT NULL DEFAULT 'CLIENTE',
  CHECK (rol IN ('CLIENTE', 'EMPLEADO', 'ADMIN')),
  
  puesto VARCHAR(100),
  url_imagen VARCHAR(255),

  creado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE servicios (
  id SERIAL PRIMARY KEY,
  titulo VARCHAR(100) NOT NLL,
  descripcion TEXT,
  precio NUMERIC(10, 2) NOT NULL,
  duracion_minutos INTEGER NOT NULL,
  categoria VARCHAR(50) NOT NULL,
  url_imagen VARCHAR(255),
  creado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE productos (
  id SERIL PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  marca VARCHAR(100),
  categoria VARCHAR(50) NOT NULL,
  descripcion TEXT,
  precio NUMERIC(10, 2) NOT NULL,
  stock INTEGER NOT NULL DEFAULT 0,
  url_imagen VARCHAR(255),
  destacado BOOLEAN DEFAULT FALSE,
  creado_en TIMESTAMPTZ NOT NULL DEFAUL CURRENT_TIMESTAMP
);

CREATE TABLE citas (
  id SERIAL PRIMARY KEY,
  cliente_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
  empleado_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE RESTRICT,
  servicio_id INTEGER NOT NULL REFERENCES servicios(id) ON DELETE RESTRICT,
  fecha_hora_inicio TIMESTAMPTZ NOT NULL,
  estado VARCHAR(15) NOT NULL DEFAULT 'PENDIENTE',
  CHECK (estado IN ('PENDIENTE', 'CONFIRMADA', 'CANCELADA', 'COMPLETADA')),
  genero VARCHAR(10),
  creado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_citas_empleado_tiempo ON citas (empleado_id, fecha_hora_inicio);
CREATE INDEX idx_citas_cliente ON citas (cliente_id);